### PR TITLE
advise that reviewers can call check package

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

**Review by maelle — APPROVED** [review]
Is there already a link to pkgcheck docs somewhere in the reviewer guide? If not it might be worth adding here?
In any case, thank you (for the docs but also the work on the API)

**Comment by mpadge** [comment]
> Is there already a link to pkgcheck docs somewhere in the reviewer guide? If not it might be worth adding here? In any case, thank you (for the docs but also the work on the API)

Good idea - and turned out to be an even better idea, coz when i revisited the text i realised the first sentence already had `pkgcheck` instructions in it. The other bits added here have nevertheless been left, because i think the repeitition here is useful.

**Review by maelle — APPROVED** [review]
:ok_hand: 

We might however change the installation instructions from remotes to pak?

**Comment by mpadge** [comment]
> ok_hand
> 
> We might however change the installation instructions from remotes to pak?

In 0.9 please! I'm trying to figure out why `covr` fails when called directly on packages which use `renv`. With Jim gone, figuring out these kinds of bugs is likely to take a while, so I personally would prefer a cautious move towards pak :crab:

**Pull request merged**
