### PR TITLE
recommend using vdiffr

### PR DESCRIPTION
**Pull request by maelle**
cf https://github.com/ropensci/software-review-meta/issues/65

cc @ropensci/editors

### CODE REVIEW

**Comment by sckott** [comment]
sounds good, though i've no experience with the pkg

**Comment by maelle** [comment]
I've used it once in a package and otherwise am trusting the good echos I've heard 🙂

**Comment by lmullen** [comment]
I am fine with this too.

My one word of caution is that we already have a *lot* of recommendations. I am concerned that it is possible that overly detailed recommendations, with the weight of tooling that accumulates around them, can impede doing the actual work of writing the packages. I would look askance at any package that didn't use "testthat," but only a highly specialized package could benefit from "vdiffr." For my own part, I wouldn't expect it for a package for which making plots is only an incidental part of the package. Put differently, I think this sort of recommendation ought to be in the "you might consider" camp rather than the "you really ought to" camp.

**Comment by sckott** [comment]
agree with @lmullen point

**Comment by melvidoni** [comment]
I also agree with @lmullen

**Comment by maelle** [comment]
Good point @lmullen, is the new phrasing better?

**Comment by lmullen** [comment]
Sure.

**Pull request merged**
