### PR TITLE
Review 1 of Portuguese translation for `bot_cheatsheet.pt.Rmd`

### PR DESCRIPTION
**Pull request by pedropark99**
This PR brings one change to the automatic output generated by the translation tools:

- Fix small typos in some sentences;

### CODE REVIEW

**Comment by pedropark99** [comment]
Weird LaTex error. I recompiled the entire book with `babelquarto::render_book` on my Windows machine, and no errors occurred.

```r
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8
[3] LC_MONETARY=Portuguese_Brazil.utf8 LC_NUMERIC=C
[5] LC_TIME=Portuguese_Brazil.utf8

time zone: America/Sao_Paulo
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] vctrs_0.6.3            cli_3.6.1              knitr_1.43
 [4] rlang_1.1.1            xfun_0.39              processx_3.8.2
 [7] purrr_1.0.1            jsonlite_1.8.7         glue_1.6.2
[10] htmltools_0.5.5        quarto_1.2             ps_1.7.5
[13] brio_1.1.3             fansi_1.0.4            rmarkdown_2.23
[16] evaluate_0.21          tibble_3.2.1           fastmap_1.1.1
[19] yaml_2.3.7             lifecycle_1.0.3        compiler_4.3.1
[22] fs_1.6.3               Rcpp_1.0.11            pkgconfig_2.0.3
[25] rstudioapi_0.15.0      later_1.3.1            digest_0.6.33
[28] R6_2.5.1               utf8_1.2.3             pillar_1.9.0
[31] magrittr_2.0.3         tools_4.3.1            withr_2.5.0
[34] babelquarto_0.0.0.9000 xml2_1.3.5
>
```

image

**Comment by pedropark99** [comment]
I was unable to reproduce the above error at my Fedora 38 machine, because the installation process of the R package `systemfonts` is failing at the linking stage of the package build. The error message:

```
/usr/bin/ld: /usr/local/lib64/libfreetype.a(ftbase.c.o): relocalização R_X86_64_32 contra ".rodata" não pode ser usada ao fazer um objecto partilhado; recompile com -fPIC
/usr/bin/ld: falha ao definir tamanhos de seção dinâmica: mau valor
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/make/shlib.mk:10: systemfonts.so] Error 1
ERROR: compilation failed for package ‘systemfonts’
* removing ‘/home/pedro/R/x86_64-redhat-linux-gnu-library/4.3/systemfonts’

The downloaded source packages are in
	‘/tmp/RtmplWNanV/downloaded_packages’
Warning message:
In install.packages("systemfonts") :
  installation of package ‘systemfonts’ had non-zero exit status

```

**Comment by pedropark99** [comment]
However, the CI pipeline in this repository that issued the weird LaTex error was running on an Ubuntu 22.04 LTS environment. That is why, I decided to use Docker to reproduce the Ubuntu environment where the CI pipeline was running on.

I used the following Dockefile on my Linux machine:

```dockerfile
FROM r-base
RUN apt-get update 
RUN apt-get install -y git libxml2-dev libssl-dev libcurl4-openssl-dev

COPY . .

RUN Rscript script.R
RUN dpkg -i quarto-1.3.450-linux-amd64.deb
RUN Rscript render.R
```

The `COPY . .` instruction was used to copy the following files from the folder tree:

```
├── dev_guide     # The dev_guide source code, using the `pedro-bot_cheatsheet.pt` branch
├── quarto-1.3.450-linux-amd64.deb       # Debian package distribution for Quarto
├── render.R     # Script to render the book using babelquarto
└── script.R       # Script to install R packages
```

The `script.R` file was:

```r
install.packages(
  c("tidyverse", "knitr", "rmarkdown",
    "airtabler",
    "babeldown",
    "babelquarto",
    "gert",
    "humaniformat",
    "rvest",
    "usethis",
    "withr",
    "brio",
    "cli",
    "fs",
    "quarto",
    "rlang",
    "sys",
    "whoami",
    "withr",
    "xml2",
    "downlit",
    "yaml")
)

install.packages('tinytex')
tinytex::install_tinytex()


install.packages('babelquarto', repos = c('https://ropensci.r-universe.dev', 'https://cloud.r-project.org'))
```

And the `render.R` file was:

```r
babelquarto::render_book("./dev_guide")
```

Using the above configurations, with an Ubuntu 22.04 LTS environment generated by the `r-base` docker image, I built the entire book succesfully with no errors. In other words, I could not reproduce once again the weird LaTex error caught during the CI pipeline run.

image

**Comment by pedropark99** [comment]
The CI pipeline that issued the LaTex error used Quarto at version "", which is newer than the version "quarto-1.3.450-linux-amd64.deb" that I used in the past test. So I decided to try one last time to reproduce the error, using the most recent version I could get of Quarto.

In this new test, I used the exact same Dockerfile as before, I just changed to Quarto version to "quarto-1.4.382-linux-amd64.deb", and once again, the entire book was builded succesfully:

image

**Comment by msperlin** [comment]
Hello,

Following an email (see below), I volunteer to help reviewing the portuguese translation of the manual.

image

Please let me know what are the next steps.

**Comment by pedropark99** [comment]
Olá @msperlin ! Tudo bem? To translate the book, we are following the guidelines described here: https://translationguide.ropensci.org/

The general idea behind it, is that we open a different Pull Request to translate each chapter or Rmd file. The translation process is divided into two reviews. I am doing always the first review, but the second review is still open for new contributors. So right now, we have some chapters waiting for this second review.

I strongly suggest you to read the guidelines I linked above, so you get a better understanding of the process. If you have any doubts about this guideline, me and @yabellini  we are here to help you 😉.

Um prazer trabalhar com você Marcelo! Abraços!

**Comment by joaojcorreia** [comment]
Hi, 

I can also help with the translation.

**Comment by danielvartan** [comment]
Bom dia Brasil!

I'm also here to help. 🙋‍♂️

**Review by msperlin — APPROVED** [review]

**Comment by msperlin** [comment]
I just approved all pending files. I looked at the portuguese text and it was all fine, except for few typos that were pointed out. 

When there are more files to review, just point it out in this chat. I suggest to leave it to the other volunteers so we can distribute the work evenly.

Best ,

**Comment by pedropark99** [comment]
Thank you for the work @msperlin ❤ !

**Comment by pedropark99** [comment]
Just popped a new PR which is ready for review 2 #717

**Pull request merged**
