### PR TITLE
Translate bot_cheatsheet.pt.Rmd to Portuguese

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by pedropark99** [comment]
Review 1 at #687.

**Comment by maelle** [comment]
@pedropark99 @msperlin In the Spanish translation we've made sure to use gender-neutral phrasing. Is "um editor" for instance gender-neutral? If not would you be able to rephrase? Thanks so much for your work and patience.

**Comment by msperlin** [comment]
Hi @maelle, 

> Is "um editor" for instance gender-neutral? 

No, its not. In portuguese, we usually use "um (a) editor (a)". @pedropark99, since you are the main author, can you please  change it directly?

**Comment by msperlin** [comment]
We might also need to check the other files for this...

**Comment by pedropark99** [comment]
Hey! I agree with @msperlin! We can reach a more "neutral gender" level by using "um (a)". I will do the change for us ✌️

**Comment by pedropark99** [comment]
Fixes at #719

**Pull request merged**
