### PR TITLE
Break up reproducibility category into component parts

### PR DESCRIPTION
**Pull request by noamross**
- Also increase clarity that software wrappers are for non-R programs
- Re-arrange thematically

Closes https://github.com/ropensci/software-review-meta/issues/81

### CODE REVIEW

**Comment by lmullen** [comment]
The thematic rearrangements looks good to me.

**Comment by noamross** [comment]
@sckott, any suggestions for other geospatial packages, esp. ones that would strain to fit into other categories?

I think @lmullen's **textreuse** is actually a good example for text.

**Comment by melvidoni** [comment]
I really like these new changes!

**Comment by sckott** [comment]
@noamross  https://github.com/ropensci/software-review/issues/174 tidync

**Pull request merged**
