### PR TITLE
add detail on test coverage expectations

### PR DESCRIPTION
**Pull request by annakrystalli**
I discussed this with Noam a while ago so just adding for clearer acceptance guidelines

### CODE REVIEW

**Comment by lmullen** [comment]
I'm a little reluctant to specify a number for test coverage. Coverage is important, to be sure, and should be measured. But I'm not sure that a single number is good as a metric of the quality of a test suite. I'd prefer to keep the line "It is good practice to write unit tests for all functions, and all package code in general" and require a test suite and the measurement of test coverage, and ask reviewers to look at that number. But I'm not sure we should specify percentages for the test suite.

**Comment by noamross** [comment]
On one hand, have a similar reluctance @lmullen.  On the other hand, we need some rules of thumb. Testing below 80% inclines me to look more carefully at the coverage before sending for review, but I can't look in detail at every test suite at the editor-check stage, so I might reply with "60% is pretty low, is there a reason for this? Otherwise we'll need to get coverage higher before sending for review". Reviewers should be looking at completeness an appropriateness of testing, but a low number makes it more likely that more cycles of review will be required.   

So maybe the language shouldn't be "75% required for acceptance", but "Test coverage below 75% is will likely need to be improved before being sent for review."

**Comment by lmullen** [comment]
@noamross That seems like a reasonable compromise. As it is currently written, the language is contradictory or ambiguous. It says that coverage has to be 75% to be accepted, but then says that below 60% is low. Saying something like what you said above, specifying a single number as a cause for a closer look rather than a rejection, seems more straightforward.

**Comment by annakrystalli** [comment]
Thanks for the feedback @lmullen & @noamross.

How about this instead?

> It is good practice to write unit tests for all functions, and all package code in general, ensuring key functionality is covered. Test coverage below 75% will likely require additional tests or explanation before being sent for review.

**Comment by noamross** [comment]
👍

**Comment by annakrystalli** [comment]
Corrected but don't have admin rights to merge it in yet. Can you @noamross ? 🙏

**Comment by maelle** [comment]
@annakrystalli did you receive the invite making you an admin of this repo?

**Comment by annakrystalli** [comment]
🤔I don't think so!

**Comment by maelle** [comment]
can you see the merge button?

**Comment by annakrystalli** [comment]
Doh! Yes! Sorted thanks

**Comment by maelle** [comment]
So much unknown power 😉

**Pull request merged**
