### PR TITLE
Fix a small typo

### PR DESCRIPTION
**Pull request by dcaseykc**
Found a small typo in 1.5. Thanks for the great resource!

### CODE REVIEW

**Comment by sckott** [comment]
hi! sorry for the delay in responding. can you instead send the PR to the branch `dev`?  https://github.com/ropensci/dev_guide/tree/dev

**Comment by dcaseykc** [comment]
@sckott Did it -- I think ...

**Comment by sckott** [comment]
@dcaseykc thanks very much! but now it looks like a bunch of other commits were added from other folks. If okay with you im going to close this PR, and make the change myself, BUT i'll attribute you by assigning you as the author and reference your handle in the news

**Comment by dcaseykc** [comment]
@sckott Go for it!

**Comment by sckott** [comment]
thanks!

**Comment by sckott** [comment]
see https://github.com/ropensci/dev_guide/pull/160/commits/790a8a6794be06e49df80d12741dafd3ffe51b8d

**Pull request closed without merging**
