### PR TITLE
set up pt translation infra

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
@pedropark99 Thanks so much for starting this translation! a

After installing the dev version of https://github.com/ropensci-review-tools/babelquarto/i

you can run `babelquarto::register_further_languages("pt")` and then `babelquarto::render_book()` will work.

**Comment by maelle** [comment]
At least this works... on my machine. Happy to fix any bug next week. :sweat_smile:

**Review by pedropark99 — APPROVED** [review]
Looks good to me.

**Comment by pedropark99** [comment]
Merci @maelle ! ✌

**Comment by maelle** [comment]
@pedropark99 can you please try running `babelquarto::register_further_languages("pt")` and then `babelquarto::render_book()`? Thank you!

**Comment by pedropark99** [comment]
Sorry @maelle! I will run these commands and commit the output.

**Pull request merged**
