### PR TITLE
Minor edits for consistency

### PR DESCRIPTION
**Pull request by adamhsparks**
Standardises the use of ":" and "." in list items to be consistent in all list items.

Corrects punctuation on line 24/25.

### CODE REVIEW

**Comment by maelle** [comment]
Thank you!! Would you mind making the PR against dev? If not, no worries, I'll edit this myself.

**Comment by adamhsparks** [comment]
Is that better?

**Comment by maelle** [comment]
Oops sorry, this became a mess, I'll re-make your edits myself but acknowledge you in the changelog.

**Comment by maelle** [comment]
And actually the template lives in another repo, I'll try to co-sign the commit there.

**Comment by maelle** [comment]
https://github.com/ropensci/software-review/commit/a54b7b69d749fb19a371c6bdcc10ea9026093d42

**Pull request closed without merging**
