### PR TITLE
update pkg_ci; closes #133

### LINKED ISSUE #133: Add more examples of Travis deploy of pkgdown website
Without travis, in a build matrix.

Poke @mpadge

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

**Comment by maelle** [comment]
Thanks a ton! Two comments

* Can you re-direct your PR to the dev branch? We now have a release cycle (once every 3 months) and edit dev only.

* Can you mention `usethis::use_pkgdown_travis()` as well?

Thanks again for sharing your experience with the community!

**Comment by maelle** [comment]
3d remark, in the same PR add your name to the bottom of index.Rmd :-)

**Comment by mpadge** [comment]
My name is already there! :smile: but thanks anyway ...

**Comment by mpadge** [comment]
Oh, and `usethis` only exports `use_pkgdown()`, but not `use_pkgdown_travis()`.

**Comment by maelle** [comment]
Yeah and I merged because I saw that the pkgdown doc you reference has all useful info anyway :-)

**Comment by mpadge** [comment]
For potential future reference here, cross-ref to [exchange with @adamhsparks](https://github.com/ropensci/bomrang/commit/da3395547b39fc034f4edd4cf2fa7ee904d8026d) to note one issue that should resolve itself without needing explicit mention:

Images in README that are stored in `vignettes` are currently not rendered in sites deployed on orphan `gh-pages` branch deployed by travis, but they are if stored in `man/figures`. The issues cited there suggest that both should work, so I presume this'll be fixed sometime soon.

**Comment by maelle** [comment]
In `rhub` repo, we have images in vignettes/figures https://github.com/r-hub/rhub/tree/master/vignettes, so I guess one should not have them directly under vignettes/?

**Comment by mpadge** [comment]
It's just the README figures that don't get transferred across if they're in `vignettes`, but your only relative-path fig is already in `man/figures`, so it all works.

**Comment by maelle** [comment]
Oh right! I hope there'll soon be a good doc of this in pkgdown, should we open an issue there?

**Comment by mpadge** [comment]
Issues are already [here](https://github.com/r-lib/pkgdown/issues/133) and [here](https://github.com/r-lib/pkgdown/issues/280), so they're aware. @hadley in that issue:
> I think current advice is to put images in man/figures - that way CRAN can access too.

CRAN advises *either* `man/figures` or `vignettes`, and images in the latter build both locally and on non-orphaned branch, but `pkgdown` does not copy `vignettes/*.img` to `articles/*.img` when deployed from travis on orphaned branch. At most, re-open one of those older issues, but only after some independent confirmation?

**Pull request closed without merging**
