### PR TITLE
add requirement and advice on testing using different R versions. 

### PR DESCRIPTION
**Pull request by annakrystalli**
Addresses #132

### CODE REVIEW

**Comment by maelle** [comment]
Thanks! 

* Could you update the NEWS in Appendix?

* Could you add examples of more complex Travis config files? E.g. https://github.com/r-hub/rhub/blob/master/.travis.yml#L5 where the different R versions are mentioned via a matrix which allows to have the pkgdown deploy from one R version only.

**Comment by annakrystalli** [comment]
Done!

**Comment by maelle** [comment]
Yay, thanks! One last thing, I hadn't see you PR-ed into master, can you PR into dev? Sorry about that.

**Comment by annakrystalli** [comment]
DOH!! My bad! brb in the correct branch 🤦‍♀️

**Pull request closed without merging**
