### PR TITLE
Add instructions to document defaults

### LINKED ISSUE #439: Recommend / mandate that all defaults are clearly documented
In many cases, the docs will read:

```r
#' @param test A logical value determining if ...
```

I think it would be much better practice and clearer for the user if this was:

```r
#' @ param test A logical value (default `TRUE`) determining if ...
```

I don't have strong feelings on the exact syntax here. The default could be indicated at the start of the end of the documentation string, it could be inside parentheses or in the main text, etc. But I believe it is really important that it is written somewhere.

### PR DESCRIPTION
**Pull request by Bisaloo**
Fix #439

### CODE REVIEW

**Review by mpadge — APPROVED** [review]
Thanks Hugo!

**Comment by maelle** [comment]
Merci !!

**Review by maelle — CHANGES_REQUESTED** [review]
Could you please also update `booknews.Rmd`? Thank you!

**Comment by maelle** [comment]
Thank you!!

**Pull request merged**
