### PR TITLE
fix: remove Twitter link and update Adam's credentials :-)

### LINKED ISSUE #842: Broken Linksoftwarereview_reviewer.Rmd
Hi! This guide is so helpful as I get ready to do my first review. Thanks rOpenSci folks.

I noticed a broken link in softwarereview_reviewer.Rmd on  line 85, which is Adam Sparks'  Twitter/X post. 

X says "...this page doesn’t exist. Try searching for something else"

I guess the reference should be removed?

### PR DESCRIPTION
**Pull request by maelle**
Fix #842

### CODE REVIEW

**Review by adamhsparks — APPROVED** [review]
Thanks, Maëlle, this should work well, I don't plan to change the URL of my webpage.

**Review by mpadge — APPROVED** [review]

**Comment by maelle** [comment]
Thanks both!

**Comment by Lextuga007** [comment]
Does this get filtered into the translation as it still appears https://github.com/ropensci/dev_guide/blob/e2d937abe632dfce3bd95dadd4443f180f93f9e7/softwarereview_reviewer.es.Rmd#L80?

**Comment by maelle** [comment]
also removed from https://github.com/ropensci/dev_guide/pull/818

Thanks so much @Lextuga007

**Pull request merged**
