### PR TITLE
Policy and guidance on GUIs

### PR DESCRIPTION
**Pull request by noamross**
Adds guidance about interactive or graphical APIs to both policies and packaging recommendations.  Also some minor re-categorization of packaging recommendations to make an "API" category.

### CODE REVIEW

**Comment by maelle** [comment]
Nice! Should this be the occasion to mention we recommend testing Shiny apps with e.g. shinytest?

**Comment by noamross** [comment]
I'd put it in testing but reference in in the GUI section, as well.  I actually am not sure of exactly what we  recommend at this point: "Shiny apps should be tested using a framework such as **shinytest** which tests that the interactive interface behaves as expected"?

**Comment by maelle** [comment]
It sounds good, many thanks, but maybe add "unit tests"? That's what shinytest allows.

**Comment by maelle** [comment]
LGTM! No opposition to your merging your PR!

**Comment by maelle** [comment]
@noamross reg code auto-generation from Shiny apps (as a special case of GUIs) do you know of any resource we could link from the guide? A (quick) search didn't help me.

**Comment by noamross** [comment]
`tabulizer` is a good example because it has an interactive workflow to extract tables, but can also only extract coordinates so one can re-run things as a script.

I'm not sure if we have anything currently in the RO suite that does code generation.  Two examples of shiny apps that do are https://gdancik.shinyapps.io/shinyGEO/, and https://github.com/wallaceEcoMod/wallace/

**Comment by maelle** [comment]
thanks!

**Pull request merged**
