### PR TITLE
Fix link to R Packages book

### PR DESCRIPTION
**Pull request by fkohrt**

### CODE REVIEW

**Review by mpadge — CHANGES_REQUESTED** [review]
Thanks @fkohrt , can you please just put " code.html" in lower case?

**Review by mpadge — APPROVED** [review]
Great, thanks!

**Comment by fkohrt** [comment]
But I'm not sure if lowercase is best, because the original file name is [`Code.html`](https://github.com/hadley/r-pkgs/blob/3e7fa18/Code.Rmd) and the IMHO redirection `code.html` → `Code.html` is done by Netlify (where "R Packages" is hosted). So you are relying on a platform-specific feature here.

**Comment by mpadge** [comment]
Oh sorry, i just tried "code.html" manually, and didn't see a re-direct. Can you then please run the {urlchecker} package on it, to get the correct version and update if needed?

**Comment by fkohrt** [comment]
Sorry, my previous comment was technically not correct:

Netlify makes the file available under both names, so no HTTP redirects are happening (and thus, {urlchecker} doesn't care). Still, I believe the original file name is the best choice in case Netlify is ever replaced by a different host.er

**Comment by fkohrt** [comment]
So, with your approval I will revert [bfced34](https://github.com/ropensci/dev_guide/pull/498/commits/bfced342f35d341955da3d45df0ce45286e52e81)

**Comment by fkohrt** [comment]
@mpadge This can be merged.

**Comment by mpadge** [comment]
Thanks @fkohrt, can you please just add a line to [the changelog](https://github.com/ropensci/dev_guide/blob/main/booknews.Rmd), and reference this PR? I'll merge then. Thank you.

**Pull request merged**
