### PR TITLE
Couple of typos fixed

### PR DESCRIPTION
**Pull request by federicomarini**
... found reading through the guide.

My way to give back for the nice set of suggestions and new ideas for pkg development I cpuld extract of this!

Federico

### CODE REVIEW

**Comment by maelle** [comment]
Many thanks @federicomarini! Could you please make a PR to the dev branch instead? Sorry about the clunky workflow, we only use master for releases. If you don't have time, that's fine, I'll use your PR to find the typos to fix.

**Comment by federicomarini** [comment]
Is it feasible directly from GitHub or do I need some extra git-fu skills?

**Comment by maelle** [comment]
I think you can at least try from the GitHub interface https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by maelle** [comment]
(but it might fail if dev is too different from master :thinking: )

**Comment by federicomarini** [comment]
I'll have a look. We do have a fallback plan just in case the merging is too nasty

**Comment by federicomarini** [comment]
Yay 😉 
image

**Comment by federicomarini** [comment]
TIL: how to change base branch of a PR ✅

**Comment by maelle** [comment]
Yay, thanks a ton!

**Pull request merged**
