### PR TITLE
add section on authorship of included code thanks to @KlausVigo

### PR DESCRIPTION
**Pull request by mpadge**
@KlausVigo Thanks again for this important idea.

### CODE REVIEW

**Review by maelle — CHANGES_REQUESTED** [review]
Thank you!

Could the line starting at https://github.com/ropensci/dev_guide/blob/66a9daa8dbff4ab403ebdda11f9e81e0695c63fd/pkg_building.Rmd#L382 refer to this section?

And what if code copied is super short, say one function from https://github.com/r-lib/rlang/blob/main/R/compat-purrr.R?

**Comment by mpadge** [comment]
@maelle I changed as you suggested above, and added the phrase, "see [... other section ...] for how to acknowledge original authors of copied code." I intentionally phrased that to avoid any direct recommendation, and so implicitly leave adherence to that at  the authors' discretion. Do you think that's okay?

**Review by maelle — COMMENTED** [review]
To me the phrasing still sounds quite strict? with a lot of "must", so I'd be worried about simple functions. Maybe adding a sentence could help? Not sure about the phrasing of said sentence though.

**Comment by mpadge** [comment]
What if i just change the initial "must" to a "should"? I tried to make the sentence as short as possible, so people would skip straight over it and directly into the quoted CRAN text, which is what really matters.

**Comment by maelle** [comment]
should sound good

**Comment by mpadge** [comment]
For the record, private comm from @maelle:

> I am at a park so not logged in, consider this my PR approval :grin:

**Pull request merged**
