### PR TITLE
add another link about "cli"

### PR DESCRIPTION
**Pull request by maelle**
Via @peterdesmet in https://github.com/ropensci/dev_guide/pull/765#discussion_r1446070465

### CODE REVIEW

**Review by yabellini — APPROVED** [review]
Looks good. :-)

**Review by mpadge — COMMENTED** [review]
I actually think this is more confusing than helpful. That guidance is very specifically for usethis only, and starting with that phrase,
> *everything* is eventually routed through `rlang`

is definitely confusing. The rest of it is then highly specific to usethis, and not readily adaptable. So i would suggest not merging this PR.

**Comment by peterdesmet** [comment]
Sounds good not to merge it, but I would like a bit more guidance for package developers. Especially the combination of CLI (advised) and silencing. In other words, if you use CLI, how can users (and you in tests) silence messages?

**Comment by mpadge** [comment]
Great point @peterdesmet. I agree that we need something, so should now modify this PR to remove usethis link, which i don't think helps, and replace with something better. Feel free to modify PR if you have any great suggestions.

**Comment by peterdesmet** [comment]
> Feel free to modify PR if you have any great suggestions.

I don't 😄 I've just started with cli, so don't know what is supported out of the box regarding silencing.

**Comment by maelle** [comment]
Does https://blog.r-hub.io/2023/11/30/cliff-notes-about-cli/#how-to-make-cli-quiet-or-not help at all? That's all I know about silencing it. That, plus creating wrappers in a package that respond to a package-level option (like usethis.quiet).

**Comment by mpadge** [comment]
I'd say almost, but not quite. I guess there's now a rather urgent need for us to draft a tech note explaining this and only this. We can then use that as the reference.

**Pull request closed without merging**
