### PR TITLE
More guidance on describing data source in DESCRIPTION #260

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
@mpadge would you have time to review this? No worries if not, thanks again for the improvement suggestion.

**Comment by mpadge** [comment]
Yes, please assign me, and i'll get on to it tomorrow

**Review by mpadge — COMMENTED** [review]
I'd only suggest including the word "both" prior to the 2 items a DESCR should contain (L#143), and maybe a helpful "brief", giving something like this: "we require that DEXCRIPTION contains both (1) A brief identification and/or description..."

**Comment by maelle** [comment]
Thank you!!

**Pull request merged**
