### PR TITLE
Review for Portuguese translation of `maintenance_marketing.pt.Rmd`

### PR DESCRIPTION
**Pull request by pedropark99**
This first review adds two changes:

- Remove a section in the last bulletpoint that is not present in the original file, to be a more precise translation of the original content.
- Fix some technical terms that got twisted in the translation.

### CODE REVIEW

**Comment by pedropark99** [comment]
This PR is ready for the 2nd review.

**Review by IldySilva — APPROVED** [review]

**Comment by IldySilva** [comment]
just made the second review #798

**Comment by pedropark99** [comment]
Thank you very much @IldySilva !!!

**Comment by rffontenelle** [comment]
I see this in "second review" column in the [project view](https://github.com/orgs/ropensci/projects/7/views/1), but it has 2 reviews. Should it go to "To be merged"?

**Comment by yabellini** [comment]
> @yabellini I agree with @rffontenelle . I also understand that this should be moved to "To be merged".

Thank you! Moved.

**Pull request merged**
